### ISSUE TITLE
Cannot load package.json on Windows

### ISSUE THREAD

**Issue by aramperes** [darionco/yarn-add-no-save#1]
When running `yarn-add-no-save` on Windows, the following exception will be raised:

```
$ yarn add-no-save (...)
$ node_modules\.bin\add-no-save (...)
(node:9740) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.resolve (path.js:166:7)
    at loadPackageJSON (node_modules\yarn-add-no-save\bin\main.js:107:27)
    at main (node_modules\yarn-add-no-save\bin\main.js:264:26)
    at Object.<anonymous> (node_modules\yarn-add-no-save\bin\local.js:15:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
(node:9740) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:9740) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 0.52s.
```

This is the function causing the error:

https://github.com/darionco/yarn-add-no-save/blob/8591888aa469466794691dfaa2d0d004bdceb491/bin/main.js#L106-L109

The problem is that Windows doesn't set the `PWD` environment variable like in UNIX.

I think the sane fix would be to use `process.cwd()` instead.

**Comment by darionco** [comment]
Thank you, fix published in 1.0.2
